# LRR library path
ifndef LRR_PATH
LRR_PATH := /home/rr/dev/free/lrr
endif
LRR_INC := $(LRR_PATH)/include
LRR_SRC := $(LRR_PATH)/src
LRR_INC_STMFAKE := $(LRR_PATH)/stm32_drv_fake/include
LRR_SRC_STMFAKE := $(LRR_PATH)/stm32_drv_fake/src

# can bus protocol definition
CAN_BUS_PRORO_INC := $(BASEDIR)/../../include